version: '2'
services:
  db:
      image: mysql:5.7
      environment:
       - MYSQL_ROOT_PASSWORD=Medusa
       - MYSQL_DATABASE=guacamole
       - MYSQL_USER=guacamole
       - MYSQL_PASSWORD=Medusa
      volumes:
       - db_data:/var/lib/mysql
      restart: always
  medusa:
      build: ./medusa_docker_image
      image: medusa:0.0.1
      command: bash -c 'sleep 15 && python db_init.py && gunicorn --bind 0.0.0.0:8000 -w 2 -k gevent --worker-connections 50 wsgi'
      ports:
       - "8000:8000"
      depends_on:
       - "db"
      volumes:
       - file_volume:/medusa_keys
       - keys:/home/opc/.oci
      restart: always

  nginx:
      build: ./nginx_docker_image
      image: medusa-nginx:0.0.1
      ports:
       - "8080:80"
      restart: always
      command: bash -c './usr/share/nginx/html/env.sh > /usr/share/nginx/html/env.js && nginx -g "daemon off;"'
      environment:
       - HOST="localhost"

  ssh:
      build: ./ssh2
      image: medusa-ssh2:0.0.1
      command: "npm start"
      ports:
       - "2222:2222"
      volumes:
       - file_volume:/SSH2-Medusa/medusa_keys
      restart: always

  node_guacd:
     build: ./node_guacd
     image: medusa-node-guacd:0.0.1
     ports:
       - "8291:8291"
     restart: always

  frontend:
    build: ./frontend
    image: medusa-frontend:0.0.1
    ports:
      - "3000:3000"
    restart: always
volumes:
  db_data:
  file_volume:
  keys:
